on: 2.1
jobs:
  nim_test_latest:
    working_directory: /usr/src/dotenv
    docker:
      - image: nimlang/nim
    steps:
      - checkout
      - run: |
          nim --version
          apt-get install -y liblmdb0
      - run:
          name: test
          command: nimble tests_functional
  nim_test_older:
    working_directory: /usr/src/dotenv
    docker:
      - image: nimlang/nim:0.18.0
    steps:
      - checkout
      - run: |
          nim --version
          apt-get install -y liblmdb0
      - run:
          name: test
          command: nimble tests_functional
workflows:
  version: 2
  build_and_test:
    jobs:
      - nim_test_latest
      - nim_test_older
